os: linux
dist: bionic
language: c
branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+(-\S*)?$/
  except:
   - appveyor
   - /^untagged/
compiler:
 - gcc
addons:
 apt:
  packages:
   - pkg-config
   - bsdtar
   - libgraphite2-dev
   - libicu-dev
   - libreadline-dev
   - libssl-dev
   - libfreetype6-dev
   - libfontconfig1-dev
   - libpng-dev
   - libexpat1-dev
   - libipc-run-perl
   - poppler-utils
env:
  global:
   - LUAROCKS=3.3.1
   - GRAPHITE=true
   - COVERAGE=false
   - LUAJIT=false
   - MAKEFLAGS="--jobs=4 --output-sync"
  jobs:
   - LUAVER=5.4.0 HARFBUZZ=2.7.0
   - LUAVER=5.3.5 HARFBUZZ=2.7.0
   - LUAVER=5.3.5 HARFBUZZ=1.4.2
   - LUAVER=5.3.5 HARFBUZZ=1.1.3
   - LUAVER=5.2.4 HARFBUZZ=2.7.0
   - LUAVER=5.1.5 HARFBUZZ=2.7.0
   - LUAJIT=true LUAVER=2.0.5 HARFBUZZ=2.7.0
   - LUAJIT=true LUAVER=2.1.0-beta3 HARFBUZZ=2.7.0
   - LUAVER=5.3.5 HARFBUZZ=2.7.0 COVERAGE=true
jobs:
  allow_failures:
   - compiler: gcc
     env: LUAVER=5.3.5 HARFBUZZ=2.7.0 COVERAGE=true
  fast_finish: true
cache:
  apt: true
  directories:
   - $HOME/local
   - $HOME/.lua
   - $HOME/.luarocks
   - $HOME/.setup_lua
   - $TRAVIS_BUILD_DIR/.fonts
   - $TRAVIS_BUILD_DIR/.sources
   - $TRAVIS_BUILD_DIR/lua_modules
   - $TRAVIS_BUILD_DIR/libtexpdf
before_install:
 - export PATH=.travis:$HOME/.lua:$PATH:$HOME/.local/bin:$HOME/.luarocks/bin
 - export LUA_HOME_DIR=$HOME/local/lua
 - export LR_HOME_DIR=$HOME/.luarocks
 - fold_unless_fail "Setup Lua & LuaRocks" "lua" setup_lua.sh $LUAVER $LUAROCKS
 - eval $(luarocks --tree lua_modules --local path)
 - export LD_LIBRARY_PATH=$HOME/local/lib:$LUA_HOME_DIR/lib:$LD_LIBRARY_PATH
 - export LIBRARY_PATH=$HOME/local/lib:$LUA_HOME_DIR/lib:$LD_LIBRARY_PATH
 - export LD_RUN_PATH=$HOME/local/lib:$LUA_HOME_DIR/lib:$LD_RUN_PATH
 - export PKG_CONFIG_PATH=$HOME/local/lib/pkgconfig:$PKG_CONFIG_PATH
 - export LUA_INCLUDE=${LUA_INCLUDE:--I$LUA_HOME_DIR/include}
 - fold_unless_fail "Setup HarfBuzz" "harfbuzz" setup_harfbuzz.sh $HARFBUZZ
install:
 - luarocks install busted
 - $COVERAGE && luarocks install cluacov || true
 - $COVERAGE && luarocks install luacov-coveralls || true
before_script:
 - eval $(luarocks --tree lua_modules --local path)
script:
 - fold_unless_fail 'Bootstrap' 'build' ./bootstrap.sh
 - fold_unless_fail 'Configure' 'build' ./configure $($LUAJIT && echo --with-luajit)
 - fold_unless_fail 'Make' 'build' make
 - $COVERAGE || fold_unless_fail 'Run busted tests' 'test' make busted
 - $COVERAGE || fold_unless_fail 'Run regression tests' 'test' make regressions
after_success:
 - $COVERAGE && travis_wait 30 make coverage || true
 - $COVERAGE && luacov-coveralls -e lua.libraries -e lua.modules -e usr || true
